apiVersion: v1
kind: Namespace
metadata:
  name: wp
---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: wp
spec:
  ports:
    - targetPort: 80
      port: 8080
      nodePort: 30008
  type: NodePort
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: wp
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
